backend:
  name: git-gateway
  branch: main

# Настройки медиа-файлов
media_folder: "images"
public_folder: "/images"

# Коллекции (типы контента)
collections:
  # Управление блюдами
  - name: "menu"
    label: "🍽️ Меню ресторана"
    files:
      - label: "Блюда"
        name: "dishes"
        file: "dishes.json"
        fields:
          - label: "Информация о ресторане"
            name: "restaurant"
            widget: "object"
            collapsed: false
            fields:
              - label: "Название (RU)"
                name: "name_ru"
                widget: "string"
                default: "Ресторан БАКУ"
              - label: "Название (EN)"
                name: "name_en"
                widget: "string"
                default: "BAKU Restaurant"
              - label: "Название (TR)"
                name: "name_tr"
                widget: "string"
                default: "BAKÜ Restoranı"
              - label: "Телефон"
                name: "phone"
                widget: "string"
                default: "+90 (242) 555-12-34"
              - label: "WhatsApp"
                name: "whatsapp"
                widget: "string"
                default: "905551234567"
              - label: "Валюта"
                name: "currency"
                widget: "string"
                default: "₺"

          - label: "Категории блюд"
            name: "categories"
            widget: "list"
            collapsed: false
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Иконка", name: "icon", widget: "string"}
              - label: "Название (RU)"
                name: "name_ru"
                widget: "string"
              - label: "Название (EN)"
                name: "name_en"
                widget: "string"
              - label: "Название (TR)"
                name: "name_tr"
                widget: "string"

          - label: "Блюда"
            name: "dishes"
            widget: "list"
            summary: "{{fields.title_ru}} - {{fields.price}}₺"
            fields:
              - {label: "ID блюда", name: "id", widget: "string"}
              - label: "Категория"
                name: "category"
                widget: "select"
                options: 
                  - {label: "⭐ Авторские", value: "signature"}
                  - {label: "🏛️ Традиционные", value: "traditional"}
                  - {label: "💎 Премиум", value: "premium"}
              - {label: "Активно", name: "active", widget: "boolean", default: true}
              - {label: "Рекомендуем", name: "featured", widget: "boolean", default: false}
              
              - label: "Название (RU)"
                name: "title_ru"
                widget: "string"
                required: true
              - label: "Название (EN)"
                name: "title_en"
                widget: "string"
                required: true
              - label: "Название (TR)"
                name: "title_tr"
                widget: "string"
                required: true
              
              - label: "Описание (RU)"
                name: "description_ru"
                widget: "text"
                required: true
              - label: "Описание (EN)"
                name: "description_en"
                widget: "text"
                required: true
              - label: "Описание (TR)"
                name: "description_tr"
                widget: "text"
                required: true
              
              - label: "Ингредиенты (RU)"
                name: "ingredients_ru"
                widget: "list"
                allow_add: true
                default: []
              - label: "Ингредиенты (EN)"
                name: "ingredients_en"
                widget: "list"
                allow_add: true
                default: []
              - label: "Ингредиенты (TR)"
                name: "ingredients_tr"
                widget: "list"
                allow_add: true
                default: []
              
              - {label: "Цена (₺)", name: "price", widget: "number", value_type: "int", min: 1}
              - {label: "Изображение", name: "image", widget: "image", required: false}
              - {label: "Рейтинг (1-5)", name: "rating", widget: "number", value_type: "float", min: 1, max: 5, step: 0.1, default: 4.0}
              - {label: "Время приготовления (мин)", name: "preparation_time", widget: "number", value_type: "int", min: 5, default: 30}
              
              - label: "Аллергены"
                name: "allergens"
                widget: "select"
                multiple: true
                required: false
                options: 
                  - {label: "🥜 Орехи", value: "nuts"}
                  - {label: "🥛 Молочные продукты", value: "dairy"}
                  - {label: "🌾 Глютен", value: "gluten"}
                  - {label: "🦐 Морепродукты", value: "seafood"}
                  - {label: "🥚 Яйца", value: "eggs"}
              
              - label: "Диетические особенности"
                name: "dietary"
                widget: "select"
                multiple: true
                required: false
                options:
                  - {label: "🥬 Вегетарианское", value: "vegetarian"}
                  - {label: "🌱 Веганское", value: "vegan"}
                  - {label: "☪️ Халяль", value: "halal"}
                  - {label: "🌾 Без глютена", value: "gluten-free"}